apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metabase

resources:
 - metabase-db.yaml
 - metabase-db-pvc.yaml
 - metabase-db-secret.yaml
 - metabase-db-service.yaml
 - metabase-deployment.yaml
