apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-db-pvc
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd